# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import komputer_pb2 as komputer__pb2


class KomputerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/komputer.KomputerService/List",
            request_serializer=komputer__pb2.KomputerListRequest.SerializeToString,
            response_deserializer=komputer__pb2.KomputerListResponse.FromString,
        )
        self.Get = channel.unary_unary(
            "/komputer.KomputerService/Get",
            request_serializer=komputer__pb2.KomputerRequest.SerializeToString,
            response_deserializer=komputer__pb2.KomputerResponse.FromString,
        )
        self.Create = channel.unary_unary(
            "/komputer.KomputerService/Create",
            request_serializer=komputer__pb2.KomputerCreateRequest.SerializeToString,
            response_deserializer=komputer__pb2.KomputerCreateResponse.FromString,
        )
        self.Update = channel.unary_unary(
            "/komputer.KomputerService/Update",
            request_serializer=komputer__pb2.KomputerUpdateRequest.SerializeToString,
            response_deserializer=komputer__pb2.KomputerUpdateResponse.FromString,
        )
        self.Delete = channel.unary_unary(
            "/komputer.KomputerService/Delete",
            request_serializer=komputer__pb2.KomputerDeleteRequest.SerializeToString,
            response_deserializer=komputer__pb2.KomputerDeleteResponse.FromString,
        )


class KomputerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KomputerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=komputer__pb2.KomputerListRequest.FromString,
            response_serializer=komputer__pb2.KomputerListResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=komputer__pb2.KomputerRequest.FromString,
            response_serializer=komputer__pb2.KomputerResponse.SerializeToString,
        ),
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=komputer__pb2.KomputerCreateRequest.FromString,
            response_serializer=komputer__pb2.KomputerCreateResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=komputer__pb2.KomputerUpdateRequest.FromString,
            response_serializer=komputer__pb2.KomputerUpdateResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=komputer__pb2.KomputerDeleteRequest.FromString,
            response_serializer=komputer__pb2.KomputerDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "komputer.KomputerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class KomputerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/komputer.KomputerService/List",
            komputer__pb2.KomputerListRequest.SerializeToString,
            komputer__pb2.KomputerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/komputer.KomputerService/Get",
            komputer__pb2.KomputerRequest.SerializeToString,
            komputer__pb2.KomputerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/komputer.KomputerService/Create",
            komputer__pb2.KomputerCreateRequest.SerializeToString,
            komputer__pb2.KomputerCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/komputer.KomputerService/Update",
            komputer__pb2.KomputerUpdateRequest.SerializeToString,
            komputer__pb2.KomputerUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/komputer.KomputerService/Delete",
            komputer__pb2.KomputerDeleteRequest.SerializeToString,
            komputer__pb2.KomputerDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
